language: node_js
node_js:
- node
env:
  global:
    secure: czG6eZFH4G2GaBES+8s8feshydOXTH3+SfVwm9AYfUaUJljPlyNVmsy6xritf+njMqmWDsGg4cGc4ZqyYiZMeDUNYVzpFB7pTUDEOIe2ztP8QfucNnO6ThVVlAJYwpD+uv3E1ECfk3psS/nMzaXw/+OwUY5Qx8fPRfeaG2AOZRxG6h1mMYO+c7af9Lbrre1nNm4HhS4T0Qodl3/wPbzf7xn0+TdfGwypCDdppcA+kbzuCWK1nc3pKeg4ezA50y1MGupdWRh8r1lITv/ziytG54GeWFnjefyQ1gnBcr4NDRKuoBRreh6maDYKF0M7GbVGUQ1xHlacjl7QwqE6TyMdVxamP7fl/a+BqEFA7Kv4i+ZPYpcwlD/KYUZWLhLrKDhvNuIj89eZggbEjKiMaoBLO5fy41PaiPSGuBXqwwLAJI2XfUJirwM0Mmr4n/zzV2wffaTcDIw88WmzVt5fbLJcoe59xRVK0VZWTw6RmoRNLrSddcAEncXlp2/UKTIwk2VU4AxHwIVlf86hPnBJ3SISp6s0k+XO6jcm2jbYGCY+/2ogYzzL52clllV9J6gxX587s/1sgbDMHmgHHD+/0vRO3F7tH7+nXuIR+27b2RKVcH1jwGjtFFANw1V9CwNzoMKWictwZMB4Cpn9i6YfkOQtUNpoYtuxfNd1qMwgsIVwEws=
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
